services:
  nfs-server:
    image: lihungte96/docker-nfs4:latest
    container_name: nfs-server
    restart: unless-stopped
    volumes:
      - ./config/nfs/exports:/etc/exports
      - nfsdata:/mnt
    networks:
      - nfsnet
    expose:
      - "2049/tcp"
      - "2049/udp"
    privileged: true

volumes:
  nfsdata:
networks:
  nfsnet:
    driver: bridge