services:
  nfs-server:
    image: lihungte96/docker-nfs4:latest
    container_name: nfs-server
    restart: unless-stopped
    volumes:
      - ./config/nfs/exports:/etc/exports
      - nfsdata:/mnt
    networks:
      - nfsnet
    expose:
      - "2049/tcp"
      - "2049/udp"
    privileged: true
  postgres_primary:
    image: bitnami/postgresql:17
    container_name: postgres_primary
    restart: unless-stopped
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=bn_bitbucket
      - POSTGRESQL_PASSWORD=bitbucketpass
      - POSTGRESQL_DATABASE=bitbucket
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
    volumes:
      - pg_primary_data:/bitnami/postgresql
      - ./config/postgresql/postgresql.conf:/opt/bitnami/postgresql/postgresql.conf
    networks:
      - pgnet

  postgres_replica:
    image: bitnami/postgresql:17
    container_name: postgres_replica
    restart: unless-stopped
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_USERNAME=bn_bitbucket
      - POSTGRESQL_PASSWORD=bitbucketpass
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
    volumes:
      - pg_replica_data:/bitnami/postgresql
      - ./config/postgresql/postgresql.conf:/opt/bitnami/postgresql/postgresql.conf
    networks:
      - pgnet

  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - PGPOOL_ADMIN_USERNAME=pgpooladmin
      - PGPOOL_ADMIN_PASSWORD=supersecureadminpass
      - PGPOOL_BACKEND_NODES=0:postgres_primary:5432,1:postgres_replica:5432
      - PGPOOL_SR_CHECK_USER=bn_bitbucket
      - PGPOOL_SR_CHECK_PASSWORD=bitbucketpass
      - PGPOOL_POSTGRES_USERNAME=bn_bitbucket
      - PGPOOL_POSTGRES_PASSWORD=bitbucketpass
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
      - PGPOOL_ENABLE_POOL_HBA=no
    volumes:
      - ./config/postgresql/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
    networks:
      - pgnet

  opensearch-node1:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch-node1
    environment:
      - cluster.name=bitbucket-opensearch
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node2,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=@1n5A!AWE@
    volumes:
      - opensearch-node1-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - opensearchnet

  opensearch-node2:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch-node2
    environment:
      - cluster.name=bitbucket-opensearch
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node3
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=@1n5A!AWE@
    volumes:
      - opensearch-node2-data:/usr/share/opensearch/data
    networks:
      - opensearchnet

  opensearch-node3:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch-node3
    environment:
      - cluster.name=bitbucket-opensearch
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=@1n5A!AWE@
    volumes:
      - opensearch-node3-data:/usr/share/opensearch/data
    networks:
      - opensearchnet

volumes:
  nfsdata:
  pg_primary_data:
  pg_replica_data:
  opensearch-node1-data:
  opensearch-node2-data:
  opensearch-node3-data:

networks:
  nfsnet:
    driver: bridge
  pgnet:
    driver: bridge
  opensearchnet:
    driver: bridge