services:
  nfs-server:
    image: lihungte96/docker-nfs4:latest
    container_name: nfs-server
    restart: unless-stopped
    volumes:
      - ./config/nfs/exports:/etc/exports
      - nfsdata:/mnt
    networks:
      - nfsnet
    expose:
      - "2049/tcp"
      - "2049/udp"
    privileged: true
  postgres_primary:
    image: bitnami/postgresql:17
    container_name: postgres_primary
    restart: unless-stopped
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=bn_bitbucket
      - POSTGRESQL_PASSWORD=bitbucketpass
      - POSTGRESQL_DATABASE=bitbucket
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
    volumes:
      - pg_primary_data:/bitnami/postgresql
      - ./config/postgresql/postgresql.conf:/opt/bitnami/postgresql/postgresql.conf
    networks:
      - pgnet

  postgres_replica:
    image: bitnami/postgresql:17
    container_name: postgres_replica
    restart: unless-stopped
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_USERNAME=bn_bitbucket
      - POSTGRESQL_PASSWORD=bitbucketpass
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pass
    volumes:
      - pg_replica_data:/bitnami/postgresql
      - ./config/postgresql/postgresql.conf:/opt/bitnami/postgresql/postgresql.conf
    networks:
      - pgnet

  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - PGPOOL_ADMIN_USERNAME=pgpooladmin
      - PGPOOL_ADMIN_PASSWORD=supersecureadminpass
      - PGPOOL_BACKEND_NODES=0:postgres_primary:5432,1:postgres_replica:5432
      - PGPOOL_SR_CHECK_USER=bn_bitbucket
      - PGPOOL_SR_CHECK_PASSWORD=bitbucketpass
      - PGPOOL_POSTGRES_USERNAME=bn_bitbucket
      - PGPOOL_POSTGRES_PASSWORD=bitbucketpass
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
      - PGPOOL_ENABLE_POOL_HBA=no
    volumes:
      - ./config/postgresql/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
    networks:
      - pgnet

volumes:
  nfsdata:
  pg_primary_data:
  pg_replica_data:

networks:
  nfsnet:
    driver: bridge
  pgnet:
    driver: bridge