services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    restart: unless-stopped
    environment:
      - SHARED_DIRECTORY=/exports
    volumes:
      - ./exports:/exports
    networks:
      - nfsnet
    ports:
      - "2049:2049"  # NFSv4

networks:
  nfsnet:
    driver: bridge